In [32]:
import numpy as np
import pandas as pd

# Base de vendas
dados_vendas = {
    'cliente_id': [101, 102, 103, 101, 104, 102, 105, 103],
    'valor': [3500.75, 189.50, np.nan, 1200.00, 450.00, np.nan, 89.90, 780.50],
    'categoria': [
        'Eletronicos',
        'Livros',
        'Roupas',
        'Eletronicos',
        'Automotivo',
        'Livros',
        'Roupas',
        'Roupas',
    ],
    'data_hora': [
        '2024-01-15 10:23:00',
        '2024-01-18 14:05:00',
        '2024-02-05 09:12:00',
        '2024-02-20 16:40:00',
        '2024-03-02 11:00:00',
        '2024-03-15 18:30:00',
        '2024-04-10 08:20:00',
        '2024-04-22 13:45:00',
    ],
    'status': [
        'Concluído',
        'Concluído',
        'Pendente',
        'Concluído',
        'Cancelado',
        'Concluído',
        'Concluído',
        'Concluído',
    ],
    'email': [
        'maria@gmail.com',
        'joao@outlook.com',
        'ana@yahoo.com',
        'maria@gmail.com',
        'carlos@gmail.com',
        'joao@outlook.com',
        'lucas@empresa.com.br',
        'ana@yahoo.com',
    ],
}

# Base de clientes
dados_clientes = {
    'cliente_id': [101, 102, 103, 104, 105],
    'nome': [
        'Maria Silva',
        'Joao Souza',
        'Ana Oliveira',
        'Carlos Lima',
        'Lucas Mendes',
    ],
    'cidade': [
        'Sao Paulo',
        'Rio de Janeiro',
        'Belo Horizonte',
        'Curitiba',
        'Salvador',
    ],
}

df_vendas = pd.DataFrame(dados_vendas)
df_clientes = pd.DataFrame(dados_clientes)

#Módulo 1 - Básico
##Diagnóstico e Limpeza
-----------------------------

##1.1 Inspeção das dimensões e resumo dos tipos de dados

### `.shape` / `.info()`

Inspecione as **dimensões** e o **resumo** dos *tipos de dados* do DataFrame df_vendas usando `.shape` e `.info()`.

In [33]:
linhas, colunas = df_vendas.shape
print(f'Dimensões: {linhas} linhas x {colunas} colunas')

Dimensões: 8 linhas x 6 colunas

In [34]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cliente_id  8 non-null      int64
 1   valor       6 non-null      float64
 2   categoria   8 non-null      object
 3   data_hora   8 non-null      object
 4   status      8 non-null      object
 5   email       8 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 516.0+ bytes

##1.2 Identificar valores nulos e Preencher registros ausentes

###`.fillna()`

Identifique os **valores nulos** e preencha os registros ausentes da coluna `valor` utilizando a mediana da respectiva categoria ou a mediana global com `.fillna()`.

In [35]:
df_vendas['valor'] = df_vendas['valor'].fillna(df_vendas['valor'].median())

##1.3 Filtrar e Exibir

###`.loc[]`
Filtre e exiba apenas as transações com status 'Concluído' e valor superior a R$ 500,00 usando `.loc[]`.

In [36]:
df_vendas.loc[(df_vendas['valor'] > 500) & (df_vendas['status'] == 'Concluído'), ['valor','status']]

     valor     status
0  3500.75  Concluído
3  1200.00  Concluído
5   615.25  Concluído
7   780.50  Concluído

#Módulo 2 - Intermediário
##Cruzamento e Transformação
-----------------------------

##2.1 Junção Relacional

###`pd.merge()`
Realize uma **junção relacional** (left merge) entre `df_vendas` e `df_clientes` utilizando a chave `cliente_id`.

In [37]:
pd.merge(df_vendas, df_clientes, on='cliente_id', how='left')

,cliente_id,valor,categoria,data_hora,status,email,nome,cidade
0,101,3500.75,Eletronicos,2024-01-15 10:23:00,Concluído,maria@gmail.com,Maria Silva,Sao Paulo
1,102,189.50,Livros,2024-01-18 14:05:00,Concluído,joao@outlook.com,Joao Souza,Rio de Janeiro
2,103,615.25,Roupas,2024-02-05 09:12:00,Pendente,ana@yahoo.com,Ana Oliveira,Belo Horizonte
3,101,1200.00,Eletronicos,2024-02-20 16:40:00,Concluído,maria@gmail.com,Maria Silva,Sao Paulo
4,104,450.00,Automotivo,2024-03-02 11:00:00,Cancelado,carlos@gmail.com,Carlos Lima,Curitiba
5,102,615.25,Livros,2024-03-15 18:30:00,Concluído,joao@outlook.com,Joao Souza,Rio de Janeiro
6,105,89.90,Roupas,2024-04-10 08:20:00,Concluído,lucas@empresa.com.br,Lucas Mendes,Salvador
7,103,780.50,Roupas,2024-04-22 13:45:00,Concluído,ana@yahoo.com,Ana Oliveira,Belo Horizonte

##2.2 Criar Nova Coluna

###`.groupby()` / `.transform()`
Crie uma nova coluna chamada `media_categoria` contendo o *valor médio* de vendas por categoria sem reduzir o número de linhas do DataFrame (utilize `.groupby()` com `.transform()`)

In [38]:
df_completo = pd.merge(df_vendas, df_clientes, on = 'cliente_id', how = 'left')
df_completo['media_categoria'] = df_completo.groupby('categoria')['valor'].transform('mean')
df_completo.head()

,cliente_id,valor,categoria,data_hora,status,email,nome,cidade,media_categoria
0,101,3500.75,Eletronicos,2024-01-15 10:23:00,Concluído,maria@gmail.com,Maria Silva,Sao Paulo,2350.375000
1,102,189.50,Livros,2024-01-18 14:05:00,Concluído,joao@outlook.com,Joao Souza,Rio de Janeiro,402.375000
2,103,615.25,Roupas,2024-02-05 09:12:00,Pendente,ana@yahoo.com,Ana Oliveira,Belo Horizonte,495.216667
3,101,1200.00,Eletronicos,2024-02-20 16:40:00,Concluído,maria@gmail.com,Maria Silva,Sao Paulo,2350.375000
4,104,450.00,Automotivo,2024-03-02 11:00:00,Cancelado,carlos@gmail.com,Carlos Lima,Curitiba,450.000000

##2.3 Contagem

###`.str.contains()`
Identifique *quantos clientes* usam o provedor de e-mail `@gmail.com` através do acessor de texto `.str.contains()`.

In [39]:
gmail = df_vendas[df_vendas['email'].str.contains('@gmail.com')]
print('Emails do Gmail:', len(gmail))

Emails do Gmail: 3

#Módulo 3 - Intermediário
##Análise Temporal e Agregação
----------------------------------------------

##3.1 Converção de Coluna

##`pd.to_datetime()`
Converta a coluna `data_hora` para o tipo datetime nativo com `pd.to_datetime()` e extraia o **mês** por extenso ou o **nome** do dia da semana utilizando o assessor `.dt`.

In [41]:
df_completo['data_hora'] = pd.to_datetime(df_completo['data_hora'])
df_completo['mes'] = df_completo['data_hora'].dt.month
df_completo[['data_hora','mes']].head()

            data_hora  mes
0 2024-01-15 10:23:00    1
1 2024-01-18 14:05:00    1
2 2024-02-05 09:12:00    2
3 2024-02-20 16:40:00    2
4 2024-03-02 11:00:00    3

#3.2 Tabela Dinâmica

##`pd.pivot_table()`
Construa uma tabela dinâmica com `pd.pivot_table()` apresentando o total `(sum)` do valor de vendas agrupado por categoria nas linhas e por cidade nas colunas, preenchendo eventuais valores nulos com zero.

In [42]:
pd.pivot_table(df_completo, values='valor', index='categoria', columns='cidade', aggfunc='sum', fill_value=0)

cidade       Belo Horizonte  Curitiba  Rio de Janeiro  Salvador  Sao Paulo
categoria
Automotivo             0.00     450.0            0.00       0.0       0.00
Eletronicos            0.00       0.0            0.00       0.0    4700.75
Livros                 0.00       0.0          804.75       0.0       0.00
Roupas              1395.75       0.0            0.00      89.9       0.00